import { Model, solve } from '@/lp';

const restrictObject = <T>(obj: { [key: string]: T }, removeKeys: string[]) =>
  Object.fromEntries(
    Object.entries(obj).filter(([k]) => !removeKeys.some((rk) => k === rk)),
  );

const removeVars = (model: Model, removeVars: string[]): Model => {
  return {
    objective: {
      ...model.objective,
      coefficients: restrictObject(model.objective.coefficients, removeVars),
    },
    constraints: model.constraints
      .map((c) => ({
        ...c,
        coefficients: restrictObject(c.coefficients, removeVars),
      }))
      .filter((c) => Object.keys(c.coefficients).length > 0),
  };
};

let model: Model = {
  objective: {
    direction: 'min',
    coefficients: {
      avo: 5,
      bcn: 5,
      bnn: 5,
      bsl: 5,
      chs: 5,
      chtom: 5,
      chrz: 5,
      cuc: 5,
      egg: 5,
      ff: 5,
      bpgrn: 5,
      ham: 5,
      brgr: 5,
      hssg: 5,
      jpno: 5,
      kw: 5,
      kstk: 5,
      let: 5,
      ndls: 5,
      onn: 5,
      pkl: 5,
      pnpl: 5,
      ptsld: 5,
      pttor: 5,
      pro: 5,
      bpred: 5,
      ronn: 5,
      rice: 5,
      smf: 5,
      straw: 5,
      tofu: 5,
      tom: 5,
      wcrs: 5,
      chili: 1,
      crmch: 1,
      mstrd: 1,
      oil: 1,
      pbtr: 1,
      pep: 1,
      salt: 1,
      vngr: 1,
      wsbi: 1,
      whcrm: 1,
      ygrt: 1,
      hmbtr: 1,
      hmspc: 1,
      hmslt: 1,
      hmsr: 1,
      hmswt: 1,
    },
  },
  constraints: [
    {
      equals: 1,
      coefficients: { hmbtr: 1, hmspc: 1, hmslt: 1, hmsr: 1, hmswt: 1 },
    },
    {
      coefficients: {
        avo: 4,
        bcn: 4,
        bnn: 4,
        bsl: 3,
        chs: 4,
        chtom: 4,
        chrz: 4,
        cuc: 4,
        egg: 4,
        ff: 12,
        bpgrn: 4,
        ham: 4,
        brgr: 12,
        hssg: 4,
        jpno: 4,
        kw: 4,
        kstk: 4,
        let: 4,
        ndls: 12,
        onn: 4,
        pkl: 4,
        pnpl: 4,
        ptsld: 12,
        pttor: 12,
        pro: 4,
        bpred: 4,
        ronn: 4,
        rice: 12,
        smf: 4,
        straw: 4,
        tofu: 4,
        tom: 4,
        wcrs: 4,
      },
      upperBound: 72,
      lowerBound: 1,
    },
    {
      coefficients: {
        chili: 1,
        crmch: 1,
        mstrd: 1,
        oil: 1,
        pbtr: 1,
        pep: 1,
        salt: 1,
        vngr: 1,
        wsbi: 1,
        whcrm: 1,
        ygrt: 1,
        hmbtr: 1,
        hmspc: 1,
        hmslt: 1,
        hmsr: 1,
        hmswt: 1,
      },
      upperBound: 4,
      lowerBound: 1,
    },
    { coefficients: { avo: 1 }, upperBound: 12 },
    { coefficients: { bcn: 1 }, upperBound: 12 },
    { coefficients: { bnn: 1 }, upperBound: 12 },
    { coefficients: { bsl: 1 }, upperBound: 12 },
    { coefficients: { chs: 1 }, upperBound: 12 },
    { coefficients: { chtom: 1 }, upperBound: 12 },
    { coefficients: { chrz: 1 }, upperBound: 12 },
    { coefficients: { cuc: 1 }, upperBound: 12 },
    { coefficients: { egg: 1 }, upperBound: 12 },
    { coefficients: { bpgrn: 1 }, upperBound: 12 },
    { coefficients: { ham: 1 }, upperBound: 12 },
    { coefficients: { hssg: 1 }, upperBound: 12 },
    { coefficients: { jpno: 1 }, upperBound: 12 },
    { coefficients: { kw: 1 }, upperBound: 12 },
    { coefficients: { kstk: 1 }, upperBound: 12 },
    { coefficients: { let: 1 }, upperBound: 12 },
    { coefficients: { onn: 1 }, upperBound: 12 },
    { coefficients: { pkl: 1 }, upperBound: 12 },
    { coefficients: { pnpl: 1 }, upperBound: 12 },
    { coefficients: { pro: 1 }, upperBound: 12 },
    { coefficients: { bpred: 1 }, upperBound: 12 },
    { coefficients: { ronn: 1 }, upperBound: 12 },
    { coefficients: { smf: 1 }, upperBound: 12 },
    { coefficients: { straw: 1 }, upperBound: 12 },
    { coefficients: { tofu: 1 }, upperBound: 12 },
    { coefficients: { tom: 1 }, upperBound: 12 },
    { coefficients: { wcrs: 1 }, upperBound: 12 },
    {
      name: 'F2-F4',
      coefficients: {
        avo: 1,
        bcn: 1,
        bnn: 1,
        bsl: 1,
        chtom: 5,
        chrz: -4,
        cuc: 1,
        bpgrn: 1,
        jpno: -3,
        kw: 5,
        onn: -3,
        pkl: 4,
        pnpl: 5,
        ptsld: 4,
        pro: 1,
        bpred: 1,
        rice: 1,
        smf: 2,
        straw: 4,
        tom: 4,
        wcrs: 1,
        chili: -12,
        crmch: 12,
        mstrd: -8,
        oil: 4,
        pep: -16,
        vngr: 20,
        wsbi: -20,
        ygrt: 16,
        hmspc: -500,
        hmsr: 500,
      },
      lowerBound: 0,
    },
    {
      name: 'F4-F0',
      coefficients: {
        avo: -3,
        bcn: -1,
        bnn: -4,
        chs: -1,
        chtom: -3,
        chrz: 4,
        egg: -1,
        ff: -2,
        bpgrn: -1,
        ham: -1,
        brgr: -6,
        hssg: -1,
        jpno: 5,
        kw: -2,
        kstk: -4,
        let: -1,
        onn: 1,
        pkl: -1,
        pnpl: -3,
        ptsld: -2,
        pttor: -2,
        pro: -2,
        bpred: -1,
        ronn: -3,
        rice: -3,
        smf: -1,
        straw: -4,
        tofu: -3,
        tom: -2,
        wcrs: 1,
        chili: 12,
        crmch: -12,
        mstrd: 12,
        pbtr: -16,
        pep: 16,
        vngr: -4,
        wsbi: 16,
        whcrm: -20,
        ygrt: -16,
        hmspc: 500,
        hmswt: -500,
      },
      lowerBound: 1,
    },
    {
      name: 'F4-F1',
      coefficients: {
        bcn: -5,
        bsl: -1,
        chs: -3,
        egg: -2,
        ff: -3,
        ham: -5,
        brgr: -12,
        hssg: -4,
        jpno: 5,
        kstk: -4,
        ndls: -4,
        onn: 3,
        ptsld: -3,
        pttor: -3,
        pro: -4,
        smf: -3,
        chili: 8,
        crmch: -12,
        mstrd: 8,
        pbtr: -12,
        pep: 12,
        salt: -20,
        wsbi: 16,
        hmspc: 500,
        hmslt: -500,
      },
      lowerBound: 1,
    },
    {
      name: 'F4-F3',
      coefficients: {
        bcn: -4,
        bsl: -4,
        chtom: -1,
        chrz: 2,
        cuc: -1,
        egg: -1,
        ff: -3,
        bpgrn: -5,
        brgr: -9,
        hssg: -4,
        jpno: 5,
        kw: -1,
        let: -2,
        onn: 2,
        pkl: -2,
        pnpl: -1,
        ptsld: -1,
        pttor: -2,
        bpred: -3,
        ronn: -1,
        smf: -3,
        tom: -1,
        wcrs: -4,
        chili: 20,
        mstrd: 8,
        oil: -4,
        pep: 8,
        salt: -4,
        vngr: -4,
        wsbi: 20,
        hmbtr: -500,
        hmspc: 500,
      },
      lowerBound: 1,
    },
    {
      name: 'MP1-MP8',
      coefficients: {
        avo: 4,
        bcn: 4,
        bnn: -1,
        chs: 2,
        chtom: 4,
        cuc: 4,
        ff: 21,
        bpgrn: 4,
        ham: 4,
        brgr: 12,
        jpno: -1,
        kw: -1,
        kstk: 4,
        let: 4,
        ndls: 3,
        onn: 4,
        pkl: 4,
        pnpl: -1,
        ptsld: 3,
        pttor: 21,
        pro: 4,
        bpred: 4,
        ronn: 4,
        rice: 3,
        smf: 4,
        straw: -1,
        tofu: 4,
        tom: 4,
        crmch: 15,
        oil: 15,
        vngr: 15,
        wsbi: -21,
        whcrm: 15,
      },
      lowerBound: 100,
    },
    {
      name: 'MP8-MP0',
      coefficients: {
        bnn: -4,
        bsl: -2,
        jpno: -4,
        kw: -4,
        ndls: -3,
        pnpl: -4,
        ptsld: -3,
        rice: -3,
        straw: -4,
        wcrs: -2,
        chili: 3,
        crmch: -20,
        mstrd: 3,
        oil: -20,
        pbtr: 3,
        pep: 3,
        salt: 3,
        vngr: -20,
        wsbi: 21,
        whcrm: -20,
        ygrt: 3,
      },
      lowerBound: -99,
    },
    {
      name: 'MP8-MP2',
      coefficients: {
        chs: -2,
        chrz: -7,
        egg: -7,
        hssg: -7,
        ndls: -3,
        ptsld: -3,
        rice: -3,
        chili: -12,
        crmch: -12,
        mstrd: -12,
        oil: -12,
        pbtr: -12,
        pep: -12,
        salt: -12,
        vngr: -12,
        wsbi: 21,
        whcrm: -12,
        ygrt: -12,
      },
      lowerBound: -99,
    },
    {
      name: 'MP8-MP3',
      coefficients: {
        bnn: -7,
        chs: -2,
        chrz: 1,
        egg: 1,
        hssg: 1,
        jpno: -7,
        kw: -7,
        ndls: -3,
        pnpl: -7,
        ptsld: -3,
        rice: -3,
        straw: -7,
        crmch: -27,
        oil: -27,
        vngr: -27,
        wsbi: 21,
        whcrm: -27,
      },
      lowerBound: -99,
    },
    {
      name: 'MP8-MP4',
      coefficients: {
        avo: 1,
        bcn: 1,
        bsl: -2,
        chtom: 1,
        cuc: 1,
        ff: -12,
        bpgrn: 1,
        ham: 1,
        brgr: 3,
        kstk: 1,
        let: 1,
        ndls: -3,
        onn: 1,
        pkl: 1,
        ptsld: -3,
        pttor: -12,
        pro: 1,
        bpred: 1,
        ronn: 1,
        rice: -3,
        smf: 1,
        tofu: 1,
        tom: 1,
        wcrs: -2,
        chili: -21,
        crmch: -15,
        mstrd: -21,
        oil: -15,
        pbtr: -21,
        pep: -21,
        salt: -21,
        vngr: -15,
        wsbi: 21,
        whcrm: -15,
        ygrt: -21,
      },
      lowerBound: -99,
    },
    // {
    //   name: 'MP8-MP7',
    //   coefficients: {
    //     bnn: 5,
    //     jpno: 5,
    //     kw: 5,
    //     ndls: -24,
    //     pnpl: 5,
    //     ptsld: -24,
    //     rice: -24,
    //     straw: 5,
    //     crmch: -15,
    //     oil: -15,
    //     vngr: -15,
    //     wsbi: 24,
    //     whcrm: -15,
    //   },
    //   lowerBound: -99,
    // },
    {
      name: 'MP8-MP9',
      coefficients: {
        avo: -7,
        bcn: -7,
        bsl: 2,
        chs: 2,
        chtom: -7,
        chrz: -4,
        cuc: -7,
        egg: -4,
        ff: 3,
        bpgrn: -7,
        ham: -7,
        brgr: -21,
        hssg: -4,
        kstk: -7,
        let: -7,
        ndls: -15,
        onn: -7,
        pkl: -7,
        ptsld: -15,
        pttor: 3,
        pro: -7,
        bpred: -7,
        ronn: -7,
        rice: -15,
        smf: -7,
        tofu: -7,
        tom: -7,
        wcrs: 2,
        crmch: -15,
        oil: -15,
        vngr: -15,
        wsbi: 9,
        whcrm: -15,
      },
      lowerBound: -100,
    },
    {
      name: 'T0-T1',
      coefficients: {
        bnn: 7,
        chrz: 12,
        ff: 20,
        hssg: -12,
        pkl: -6,
        pttor: -20,
        straw: -7,
        tofu: 6,
        whcrm: 4,
      },
      lowerBound: 0,
    },
    {
      name: 'T1-T2',
      coefficients: {
        egg: -12,
        ff: -20,
        hssg: 12,
        pkl: 6,
        pttor: 20,
        pro: -6,
        straw: 7,
        whcrm: -4,
      },
      lowerBound: 0,
    },
    // {
    //   name: 'T1-T3',
    //   coefficients: {
    //     chrz: -12,
    //     bpgrn: -6,
    //     hssg: 12,
    //     kw: -7,
    //     ndls: -30,
    //     pkl: 6,
    //     rice: 30,
    //     straw: 7,
    //   },
    //   lowerBound: 0,
    // },
    {
      name: 'T1-T4',
      coefficients: {
        ff: -20,
        ham: -6,
        ndls: -30,
        pkl: 6,
        pnpl: -7,
        pttor: 20,
        rice: 30,
        straw: 7,
        mstrd: -2,
        whcrm: -4,
      },
      lowerBound: 0,
    },
    // {
    //   name: 'T1-T5',
    //   coefficients: {
    //     bcn: -6,
    //     egg: -12,
    //     hssg: 12,
    //     jpno: -7,
    //     ndls: -30,
    //     pkl: 6,
    //     rice: 30,
    //     straw: 7,
    //     mstrd: -2,
    //   },
    //   lowerBound: 0,
    // },
    {
      name: 'T1-T6',
      coefficients: {
        bnn: -7,
        chtom: -6,
        chrz: -12,
        ff: -20,
        hssg: 12,
        pkl: 6,
        ptsld: -30,
        pttor: 20,
        rice: 30,
        straw: 7,
        crmch: -4,
      },
      lowerBound: 0,
    },
    {
      name: 'T1-T7',
      coefficients: { pkl: 6, ptsld: -30, ronn: -6, rice: 30, oil: -4 },
      lowerBound: 0,
    },
    {
      name: 'T1-T8',
      coefficients: {
        egg: -12,
        ff: -20,
        brgr: -18,
        hssg: 12,
        pkl: 6,
        ptsld: -30,
        pttor: 20,
        rice: 30,
        straw: 7,
        crmch: -4,
        pbtr: -2,
      },
      lowerBound: 0,
    },
    {
      name: 'T1-T9',
      coefficients: {
        bsl: -1,
        chrz: -12,
        hssg: 12,
        kw: -7,
        pkl: 6,
        bpred: -6,
        straw: 7,
        wcrs: 1,
        oil: -4,
        pbtr: -2,
      },
      lowerBound: 0,
    },
    {
      name: 'T1-T10',
      coefficients: {
        bsl: -1,
        cuc: -6,
        ff: -20,
        pkl: 6,
        pnpl: -7,
        pttor: 20,
        straw: 7,
        wcrs: 1,
        chili: -2,
        crmch: -4,
      },
      lowerBound: 0,
    },
    {
      name: 'T1-T11',
      coefficients: {
        bsl: -1,
        egg: -12,
        hssg: 12,
        jpno: -7,
        let: -6,
        pkl: 6,
        straw: 7,
        wcrs: 1,
        chili: -2,
        oil: -4,
      },
      lowerBound: 0,
    },
    // {
    //   name: 'T1-T12',
    //   coefficients: {
    //     bnn: -7,
    //     bsl: -1,
    //     chrz: -12,
    //     ff: -20,
    //     hssg: 12,
    //     ndls: -30,
    //     pkl: 6,
    //     pttor: 20,
    //     rice: 30,
    //     straw: 7,
    //     wcrs: 1,
    //     salt: -2,
    //     wsbi: -2,
    //   },
    //   lowerBound: 0,
    // },
    {
      name: 'T1-T13',
      coefficients: {
        bsl: -1,
        ndls: -30,
        onn: -6,
        pkl: 6,
        rice: 30,
        wcrs: 1,
        salt: -2,
        vngr: -4,
        wsbi: -2,
      },
      lowerBound: 0,
    },
    // {
    //   name: 'T1-T14',
    //   coefficients: {
    //     bsl: -1,
    //     egg: -12,
    //     ff: -20,
    //     hssg: 12,
    //     kstk: -6,
    //     ndls: -30,
    //     pkl: 6,
    //     pttor: 20,
    //     rice: 30,
    //     straw: 7,
    //     wcrs: 1,
    //     pep: -2,
    //     wsbi: -2,
    //   },
    //   lowerBound: 0,
    // },
    {
      name: 'T1-T15',
      coefficients: {
        avo: -6,
        bsl: -1,
        chrz: -12,
        hssg: 12,
        kw: -7,
        pkl: 6,
        ptsld: -30,
        rice: 30,
        straw: 7,
        wcrs: 1,
        pep: -2,
        vngr: -4,
        wsbi: -2,
      },
      lowerBound: 0,
    },
    // {
    //   name: 'T1-T16',
    //   coefficients: {
    //     bsl: -1,
    //     ff: -20,
    //     pkl: 6,
    //     pnpl: -7,
    //     ptsld: -30,
    //     pttor: 20,
    //     rice: 30,
    //     smf: -6,
    //     straw: 7,
    //     wcrs: 1,
    //     wsbi: -2,
    //     ygrt: -2,
    //   },
    //   lowerBound: 0,
    // },
    {
      name: 'T1-T17',
      coefficients: {
        bsl: -1,
        egg: -12,
        hssg: 12,
        jpno: -7,
        pkl: 6,
        ptsld: -30,
        rice: 30,
        straw: 7,
        tom: -6,
        wcrs: 1,
        vngr: -4,
        wsbi: -2,
        ygrt: -2,
      },
      lowerBound: 0,
    },
    {
      upperBound: 280,
      coefficients: {
        bnn: 7,
        chs: 5,
        chrz: 12,
        ff: 20,
        rice: 30,
        tofu: 6,
        wcrs: 1,
        whcrm: 4,
        hmbtr: 250,
        hmspc: 250,
        hmslt: 250,
        hmsr: 250,
        hmswt: 250,
      },
    },
  ],
};

// model = removeVars(model, [
//   // 'avo',
//   // 'chili',
//   // 'crmch',

//   // 'mstrd',
//   // 'oil',
//   // 'pbtr',
//   // 'pep',
//   // 'salt',
//   // 'vngr',
//   // 'wsbi',
//   // 'whcrm',
//   // 'ygrt',

//   // 'tofu',
//   // 'tom',
//   // 'wcrs',

//   // 'bcn',
//   // 'bnn',
//   // 'bsl',
//   // 'chs',
//   // 'chtom',

//   // 'chrz',
//   // 'cuc',
//   // 'egg',
//   // 'ff',
//   // 'bpgrn',
//   // 'ham',
//   // 'brgr',
//   // 'hssg',
//   // 'jpno',
//   // 'kw',
//   // 'kstk',
//   // 'let',
//   // 'ndls',
//   // 'onn',
//   // 'pkl',
//   // 'pnpl',
//   // 'ptsld',
//   // 'pttor',
//   // 'pro',
//   // 'bpred',
//   // 'ronn',
//   // 'rice',
//   // 'smf',
//   // 'straw',
//   // 'hmbtr',
//   // 'hmspc',
//   // 'hmslt',
//   // 'hmsr',
//   // 'hmswt',
// ]);

solve(model)
  .then((res) => {
    console.log(res);
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
