name: 'Checks'
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: ^7

      - uses: actions/checkout@v3 # checkout the repo

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test --ci

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          reporter: jest-junit # Format of test results
          path: junit.xml
          name: Unit Tests # Name of the check run which will be created
